//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by View model template for Invoice Tracker.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using InvoiceTracker.Controllers;
using InvoiceTracker.Database;

namespace InvoiceTracker.Views
{
	public partial interface IActorView
	{
		string Honorific { get; set; }
		string FirstName { get; set; }
		string MiddleName { get; set; }
		string LastName { get; set; }
		string PhoneNumber { get; set; }
		string Email { get; set; }
		int Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.ActorController cntrl);
	}

	public partial interface IConsultant_ContactView
	{
		int Id { get; set; }
		int? Consultant_Id { get; set; }
		int? Actor_Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.Consultant_ContactController cntrl);
	}

	public partial interface IConsultantView
	{
		string Name { get; set; }
		string Address1 { get; set; }
		string Address2 { get; set; }
		string City { get; set; }
		string State { get; set; }
		string Zip { get; set; }
		short? PhoneNumber { get; set; }
		string Email { get; set; }
		int Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.ConsultantController cntrl);
	}

	public partial interface IDeliverableView
	{
		int Id { get; set; }
		string Name { get; set; }
		DateTime? DueDate { get; set; }
		string IsComplete { get; set; }
		decimal? ProjectedCost { get; set; }
		decimal? ActualCost { get; set; }
		string Description { get; set; }
		DateTime? StartDate { get; set; }
		DateTime? ProjectedFinishDate { get; set; }
		DateTime? ActualFinishDate { get; set; }
		string File { get; set; }
		DateTime? CreationDate { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.DeliverableController cntrl);
	}

	public partial interface IEmployeeView
	{
		int Id { get; set; }
		string EmployeeId { get; set; }
		int? Actor_Id { get; set; }
		int? Unit_Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.EmployeeController cntrl);
	}

	public partial interface IEncumberanceView
	{
		int Id { get; set; }
		int? Project_Id { get; set; }
		int? Consultant_Id { get; set; }
		int? SOW_Id { get; set; }
		string TaskOrder { get; set; }
		string ObjCategory { get; set; }
		string Object { get; set; }
		string Percentage { get; set; }
		string Amount { get; set; }
		string AcesNo { get; set; }
		string EcapsDocId { get; set; }
		string File { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.EncumberanceController cntrl);
	}

	public partial interface IInvoiceView
	{
		int Id { get; set; }
		int? Project_Id { get; set; }
		string InvoiceNumber { get; set; }
		DateTime? FromDate { get; set; }
		DateTime? ToDate { get; set; }
		DateTime? ReceiptDate { get; set; }
		DateTime? ApprovalDate { get; set; }
		DateTime? DispersalDate { get; set; }
		string ContractNumber { get; set; }
		string IsPaid { get; set; }
		string File { get; set; }
		int? Consultant_Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.InvoiceController cntrl);
	}

	public partial interface INTPView
	{
		int Id { get; set; }
		int? SOW_Id { get; set; }
		string File { get; set; }
		string DispersalDate { get; set; }
		string CreationDate { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.NTPController cntrl);
	}

	public partial interface IProject_ActorView
	{
		int Id { get; set; }
		int? Project_Id { get; set; }
		int? Actor_Id { get; set; }
		int? Role_Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.Project_ActorController cntrl);
	}

	public partial interface IProject_DeliverableView
	{
		int Id { get; set; }
		int? Project_Id { get; set; }
		int? Deliverable_Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.Project_DeliverableController cntrl);
	}

	public partial interface IProject_FinancialView
	{
		int Id { get; set; }
		int? Project_Id { get; set; }
		string PCA { get; set; }
		DateTime? ExpirationDate { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.Project_FinancialController cntrl);
	}

	public partial interface IProject_NoteView
	{
		string Id { get; set; }
		int? Project_Id { get; set; }
		int? User_Id { get; set; }
		string Note { get; set; }
		DateTime? CreationDate { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.Project_NoteController cntrl);
	}

	public partial interface IProjectView
	{
		int Id { get; set; }
		string Name { get; set; }
		string Summary { get; set; }
		string SuperDistrict { get; set; }
		bool IsComplete { get; set; }
		string ProjectId { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.ProjectController cntrl);
	}

	public partial interface IRoleView
	{
		int Id { get; set; }
		string Name { get; set; }
		string Description { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.RoleController cntrl);
	}

	public partial interface ISOW_TaskView
	{
		int Id { get; set; }
		int? SOW_Id { get; set; }
		int? Task_Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.SOW_TaskController cntrl);
	}

	public partial interface ISOWView
	{
		int Id { get; set; }
		int? Project_Financial_Id { get; set; }
		int? Consultant_Id { get; set; }
		string WorkOrderNumber { get; set; }
		string NotToExceedTotal { get; set; }
		string File { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.SOWController cntrl);
	}

	public partial interface ITask_DeliverableView
	{
		int Id { get; set; }
		int? Task_Id { get; set; }
		int? Deliverable_Id { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.Task_DeliverableController cntrl);
	}

	public partial interface ITaskView
	{
		int Id { get; set; }
		string Name { get; set; }
		string ProjectedCost { get; set; }
		string ActualCost { get; set; }
		string Description { get; set; }
		string PercComplete { get; set; }
		string IsComplete { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.TaskController cntrl);
	}

	public partial interface IUnitView
	{
		int Id { get; set; }
		string UnitNumber { get; set; }
		string SectionNumber { get; set; }
		string Name { get; set; }
		string DivisionNumber { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.UnitController cntrl);
	}

	public partial interface IUserView
	{
		int Id { get; set; }
		int? Actor_Id { get; set; }
		string ComputerName { get; set; }
		DateTime? CreationDate { get; set; }
		InvoiceTrackerDB Model { get; set; }

		void AddListner(Controllers.UserController cntrl);
	}

}

